# Generated by Django 4.1.2 on 2022-10-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVTNunez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
